name: VariaMosPLE_LINT

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:

  linter:
    name: Super-linter
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - name: Super-Linter
      uses: github/super-linter@v4.9.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISABLE_ERROR: true
#        LOG_FILE: log_file_from_super-linter
        VALIDATE_MARKDOWN: true #Markdown only for the moment because an analysis can take a few minutes

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


